baseURL = "https://python-exercises.netlify.com"
theme = "risotto"
title = "Python Exercises"
author = "Domiziano Scarcelli"
copyright = "© [Domiziano Scarcelli](https://domiziano.netlify.com)"
paginate = 3
languageCode = "it"
DefaultContentLanguage = "it"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

# Automatically add content sections to main menu
sectionPagesMenu = "main"

[params]
noindex = false

[params.theme]
palette = "base16-dark"

# Sidebar: about/bio
[params.about]
title = "python-exercises"
description = "A collection of Python exercises for beginners and intermediate learners. If you find some errors, please open an issue on [GitHub](https://github.com/DomizianoScarcelli/python-exercises)"
logo = "images/python_logo.webp"

# Sidebar: social links
# Available icon sets:
# * FontAwesome 6 <https://fontawesome.com/> ('fa-brands', 'fa-normal', or 'fa-solid' for brands)
# * Academicons <https://jpswalsh.github.io/academicons> ('ai ai-')

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/DomizianoScarcelli/python-exercises"

# [[params.socialLinks]]
# icon = "fa-solid fa-envelope"
# title = "Email"
# url = "mailto:example@example.com"

# [[params.socialLinks]]
# icon = "ai ai-orcid"
# title = "ORCID"
# url = "https://orcid.org/0000-0001-2345-6789"

# [menu]

#   [[menu.main]]
#     identifier = "about"
#     name = "About"
#     url = "/about/"
#     weight = 10

[taxonomies]
category = "categories"
tag = "tags"
# series = "series"

# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true

[markup]

  # Table of contents
  # Add toc = true to content front matter to enable
  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = true

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
defaultContentLanguage = 'it'
defaultContentLanguageInSubdir = true
[languages]
  [languages.it]
    contentDir = 'content/it'
    disabled = false
    languageCode = 'it-IT'
    languageDirection = 'ltr'
    languageName = 'Italian'
    title = 'Esercizi Python'
    weight = 1
  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Python Exercises'
    weight = 2

[[module.mounts]]
source = "content/en"
target = "content"
lang = "en"

[[module.mounts]]
source = "content/it"
target = "content"
lang = "it"
